### ISSUE TITLE
Help in events needed

### ISSUE THREAD

**Issue by ySnoopyDogy** [ySnoopyDogy/menheraRewrite#1]
OOOi tsutsu/nayu, eu tentei fazer o esquema dos eventos, usei como base a Amandinha e a atual Menhera, e meio que não funcionou

Eu tambem imagino que esse tipo de organização seja ruim pros eventos, ou algo assim

@Tsugami @NavyCake Quanto algum de voces estiverem disponíveis e puder ajudar, agradeço >...<

Com amor, Lux.

**Comment by Tsugami** [comment]
Quando eu vi esse no meu email, pensei que era uma carta kk

**Comment by Tsugami** [comment]
https://github.com/ySnoopyDogy/menheraRewrite/blob/master/src/events/readyEvent.ts#L6-L9
```ts
interface IEvent {
 name: string;
 run: (bot: MenheraClient, ...args: uknown[]): uknown;
}
```

Primeiro parametro do `run` é o bot e depois vem os parametros do Event, no caso de [`CREATE_MESSAGE`](https://abal.moe/Eris/docs/Client#event-messageCreate), seria [`Message`](https://abal.moe/Eris/docs/Client#event-messageCreate) por exemplo.

**Comment by NavyCake** [comment]
🤔 Acho que não precisa um parametro do bot ali ... pois tem evento que retorna o client ...

**Comment by Tsugami** [comment]
Não, o MenheraClient não estende o client do eris

**Comment by ySnoopyDogy** [comment]
Ok novidades sobre o problema
Depois de alguns console log, constatei que o evento abre limpo, e so funciona se eu criar um constructor aleatorio, mas o event.name ainda fica indisponivel, vou commitar minhas gambiarras

**Comment by Tsugami** [comment]
branch separado pls
